name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    # Locates the subfolder containing package.json
    - name: Find Project Root
      id: find-path
      run: |
        TARGET_DIR=$(find . -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \+ | head -n 1)
        echo "project_path=${TARGET_DIR}" >> $GITHUB_OUTPUT

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      working-directory: ${{ steps.find-path.outputs.project_path }}
      run: npm install

    - name: Build Source
      working-directory: ${{ steps.find-path.outputs.project_path }}
      run: npm run build --if-present

    - name: Run Tests
      working-directory: ${{ steps.find-path.outputs.project_path }}
      run: npm test
